-- ════════════════════════════════════════════════════════════════
-- EINHAUS REFA-Zeitaufnahme – Tabelle für Kapazitätsplanung
-- Einmalig im Supabase SQL-Editor ausführen.
-- Jede Zeile = ein gemessener Zyklus (ein Prozessschritt, ein Bauteil).
-- ════════════════════════════════════════════════════════════════

create table if not exists public.zeitaufnahme (
    id             bigint generated by default as identity primary key,
    datum          date        not null,
    kabine         text        not null,
    bauteil        text        not null,
    prozessschritt text        not null,
    zyklus_nr      integer     not null,
    istzeit_sek    numeric     not null,
    leistungsgrad  numeric     not null default 100,
    normalzeit_sek numeric     not null,
    bemerkung      text,
    erfasser       text,
    created_at     timestamptz not null default now()
);

create index if not exists zeitaufnahme_gruppe_idx
    on public.zeitaufnahme (kabine, bauteil, prozessschritt);

-- Row Level Security aktivieren
alter table public.zeitaufnahme enable row level security;

-- Anon-Key darf lesen, einfügen und löschen (Löschen = Ausreißer/Fehlmessungen entfernen)
create policy "anon select zeitaufnahme"
    on public.zeitaufnahme for select
    to anon
    using (true);

create policy "anon insert zeitaufnahme"
    on public.zeitaufnahme for insert
    to anon
    with check (true);

create policy "anon delete zeitaufnahme"
    on public.zeitaufnahme for delete
    to anon
    using (true);
