-- ════════════════════════════════════════════════════════════════
-- EINHAUS REFA-Zeitaufnahme – Tabelle für Kapazitätsplanung
-- Einmalig im Supabase SQL-Editor ausführen.
-- Jede Zeile = ein gemessener Zyklus (ein Prozessschritt, ein Bauteil).
-- ════════════════════════════════════════════════════════════════

create table if not exists public.zeitaufnahme (
    id             bigint generated by default as identity primary key,
    datum          date        not null,
    kabine         text        not null,
    bauteil        text        not null,
    prozessschritt text        not null,
    zyklus_nr      integer     not null,
    istzeit_sek    numeric     not null,
    leistungsgrad  numeric     not null default 100,
    normalzeit_sek numeric     not null,
    bemerkung      text,
    erfasser       text,
    created_at     timestamptz not null default now()
);

create index if not exists zeitaufnahme_gruppe_idx
    on public.zeitaufnahme (kabine, bauteil, prozessschritt);

-- Row Level Security aktivieren
-- Haertung 31.08.2026 (Sicherheits-Review, Manuel Einhaus): anon-Policies
-- entfernt (waren using(true)/with check(true) fuer select/insert/delete -
-- zusammen mit dem oeffentlich eingebetteten anon-Key konnte jeder im
-- Internet die Tabelle lesen, befuellen und leeren). Diese Kopie ist zudem
-- veraltet: REFA-Zeitaufnahme laeuft produktiv im separaten Repo
-- zeitaufnahme-lackierung (eigenes Supabase_Tabelle.sql, ebenfalls zu
-- haerten). Dieses Supabase-Projekt ist dauerhaft abgeschaltet (kein
-- Restore, Entscheidung Manuel 26.08.2026). Ohne Policy verweigert RLS per
-- Default jeden Zugriff - Zugriff nur noch ueber service_role/Backend.
alter table public.zeitaufnahme enable row level security;
