-- ════════════════════════════════════════════════════════════════
-- EINHAUS OEE – Tabelle für den Beflammroboter
-- Einmalig im Supabase SQL-Editor ausführen.
-- Schema identisch zu oee_erfassung (Lackierroboter Kabine 1),
-- aber eigene Tabelle, damit beide Roboter getrennt erfasst werden.
-- ════════════════════════════════════════════════════════════════

create table if not exists public.oee_beflammroboter (
    id                bigint generated by default as identity primary key,
    datum             date        not null,
    schicht           text,
    belegungszeit_min integer,
    stoerung_min      integer,
    gesamtmenge       integer,
    ausschuss         integer,
    verfuegbarkeit    numeric,
    qualitaet         numeric,
    oee               numeric,
    notiz             text,
    created_at        timestamptz not null default now()
);

-- Row Level Security aktivieren
alter table public.oee_beflammroboter enable row level security;

-- Anon-Key darf lesen und einfügen (wie bei oee_erfassung)
create policy "anon insert oee_beflammroboter"
    on public.oee_beflammroboter for insert
    to anon
    with check (true);

create policy "anon select oee_beflammroboter"
    on public.oee_beflammroboter for select
    to anon
    using (true);
