-- ════════════════════════════════════════════════════════════════
-- EINHAUS OEE – Tabelle für den Beflammroboter
-- Einmalig im Supabase SQL-Editor ausführen.
-- Schema identisch zu oee_erfassung (Lackierroboter Kabine 1),
-- aber eigene Tabelle, damit beide Roboter getrennt erfasst werden.
-- ════════════════════════════════════════════════════════════════

create table if not exists public.oee_beflammroboter (
    id                bigint generated by default as identity primary key,
    datum             date        not null,
    schicht           text,
    belegungszeit_min integer,
    stoerung_min      integer,
    gesamtmenge       integer,
    ausschuss         integer,
    verfuegbarkeit    numeric,
    qualitaet         numeric,
    oee               numeric,
    notiz             text,
    created_at        timestamptz not null default now()
);

-- Row Level Security aktivieren
-- Haertung 31.08.2026 (Sicherheits-Review, Manuel Einhaus): anon-Policies
-- entfernt (waren using(true)/with check(true), zusammen mit dem oeffentlich
-- eingebetteten anon-Key voller Lese-/Schreibzugriff fuer jeden im Internet).
-- OEE Beflammroboter ist laengst auf einhaus-report migriert (Erfassung +
-- Auswertung); dieses Supabase-Projekt ist dauerhaft abgeschaltet (kein
-- Restore, Entscheidung Manuel 26.08.2026). Ohne Policy verweigert RLS per
-- Default jeden Zugriff - Zugriff nur noch ueber service_role/Backend.
alter table public.oee_beflammroboter enable row level security;
